language: php

dist: trusty

sudo: false

php:
    - '7.2'
    - '7.3'

cache:
    directories:
        - ~/.composer/cache/files

env:
    global:
        - APP_ENV=test

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer install --no-interaction --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:database:create -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create -vvv)

script:
    - composer validate --strict
    - composer check-style
    - composer analyse
    - composer test
    - vendor/bin/ecs check src/ tests/ spec/
    - vendor/bin/phpstan analyse src --level max -c phpstan.neon
    - vendor/bin/phpspec run

    - vendor/bin/phpunit